export enum POWER {
  ON = 1,
  OFF = 0,
  POWER_ON = 'POWER_ON',
  POWER_OFF = 'POWER_OFF'
}

export enum MODE {
  NORMAL = 0,
  STRICT = 1,
  TOGGLE_MODE = 'TOGGLE_MODE'
}

export enum TURN {
  PLAYER_AI = 'PLAYER_AI_TURN',
  PLAYER_AI_FINISHED = 'PLAYER_AI_FINISHED',
  PLAYER_HUMAN = 'PLAYER_HUMAN_TURN',
  MOVE_COMPLETED = 'MOVE_COMPLETED',
  VALIDATE_PLAYER_MOVE = 'VALIDATE_PLAYER_MOVE',
  VALID_MOVE = 'VALID_MOVE',
  INVALID_MOVE = 'INVALID_MOVE'
}

export enum PLAY {
  START_GAME = 'START_GAME',
  END_GAME = 'END_GAME'
}

export enum PATTERN {
  PREV_LEVEL = 'PREV_LEVEL',
  NEXT_LEVEL = 'NEXT_LEVEL',
  REPEAT_LEVEL = 'REPEAT_LEVEL',
  RESET_LEVEL = 'RESET_LEVEL',
  RESET = 'RESET'
}

export enum PLAYER_PATTERN {
  RECORD_PLAYER_PATTERN = 'RECORD_PLAYER_PATTERN',
  RESET_PLAYER_PATTERN = 'RESET_PLAYER_PATTERN'
}

export enum RESET {
  RESET_STATE = 'RESET_STATE'
}
